@host = http://localhost:5254

### Get a specific patient by id.
@id = 5

GET {{host}}/patients/{{id}}
Accept: application/json

### Request a patient that does not exist.
GET {{host}}/patients/999
Accept: application/json